version: "3"
services:
  app:
    build: ./docker/go
    container_name: go-clean-app
    tty: true
    volumes:
      - ./:/go-clean-app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12.3
    container_name: go-clean-app-db
    volumes:
      - ./docker/postgresql/data:/var/lib/pgsql
    ports:
      - 5433:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: "postgres"
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
